ALTER TABLE users ALTER COLUMN user_image_uri DROP DEFAULT;
ALTER TABLE users ALTER COLUMN user_image_uri DROP NOT NULL;

ALTER TABLE users ALTER COLUMN company_name DROP DEFAULT;
ALTER TABLE users ALTER COLUMN company_name DROP NOT NULL;

ALTER TABLE users ALTER COLUMN user_name DROP DEFAULT;
ALTER TABLE users ALTER COLUMN user_name DROP NOT NULL;

ALTER TABLE users ALTER COLUMN company_image_uri DROP DEFAULT;
ALTER TABLE users ALTER COLUMN company_image_uri DROP NOT NULL;
