ALTER TABLE users ADD IF NOT EXISTS user_image_uri TEXT DEFAULT '' NOT NULL;
ALTER TABLE users ADD IF NOT EXISTS company_name TEXT DEFAULT '' NOT NULL;
ALTER TABLE users ADD IF NOT EXISTS user_name TEXT DEFAULT '' NOT NULL;
ALTER TABLE users ADD IF NOT EXISTS company_image_uri TEXT DEFAULT '' NOT NULL;

ALTER TABLE users ALTER COLUMN user_image_uri SET DEFAULT '';
ALTER TABLE users ALTER COLUMN user_image_uri SET NOT NULL;

ALTER TABLE users ALTER COLUMN company_name SET DEFAULT '';
ALTER TABLE users ALTER COLUMN company_name SET NOT NULL;

ALTER TABLE users ALTER COLUMN user_name SET DEFAULT '';
ALTER TABLE users ALTER COLUMN user_name SET NOT NULL;

ALTER TABLE users ALTER COLUMN company_image_uri SET DEFAULT '';
ALTER TABLE users ALTER COLUMN company_image_uri SET NOT NULL;